urls.py
"""
HELIUM 2
(c) 2017 Evan Chen
See LICENSE.txt for details.

urls.py

Pretty self-explanatory.

CONVENTION: Name of view function is always the URL
with all dashes and slashes replaced by underscores
The corresponding template, if applicable, uses the URL name
"""

from django.conf.urls import url
import helium.views as views
urlpatterns = [
	url(r'^grade-scans/([0-9]+)/$', views.grade_scans),
	url(r'^grade-scans/redir/$', views.grade_scans_redir, name='grade_scans_redir'),
	url(r'^old-grader/exam/([0-9]+)/$', views.old_grader_exam),
	url(r'^old-grader/exam/redir/$', views.old_grader_exam_redir, name='old_grader_exam_redir'),
	url(r'^old-grader/problem/([0-9]+)/$', views.old_grader_problem),
	url(r'^old-grader/problem/redir/$', views.old_grader_problem_redir, name='old_grader_problem_redir'),
	url(r'^fast-match/([0-9]+)/$', views.fast_match),
	url(r'^fast-match/redir/$', views.fast_match_redir, name='fast_match_redir'),
	url(r'^fast-match/([0-9]+)/(attention)/$', views.fast_match),
	url(r'^fast-match/redir/(attention)/$', views.fast_match_redir),
	url(r'^view-verdict/([0-9]+)/$', views.view_verdict),
	url(r'^view-verdicts/conflict-all/$', views.view_conflicts_all, name='view_conflicts_all'),
	url(r'^view-verdicts/conflict-own/$', views.view_conflicts_own, name='view_conflicts_own'),
	url(r'^view-verdicts/comedy/([0-9]+)/$', views.view_comedy, name='view_comedy'),
	url(r'^find-paper/$', views.find_paper, name='find_paper'),
	url(r'^view-paper/scan/([0-9]+)/$', views.view_paper, name='view_paper_scan'),
	url(r'^view-paper/([0-9]+)/([0-9]+)/$', views.view_paper),
	url(r'^estimation-calc/$', views.estimation_calc, name='estimation_calc'),
	url(r'^upload-scans/$', views.upload_scans, name='upload_scans'),
	url(r'^view-pdf/([0-9]+)/$', views.view_pdf, name='view_pdf'),
	url(r'^view-pdf/redir/$', views.view_pdf_redir, name='view_pdf_redir'),
	url(r'^view-task/([0-9]+)/$', views.view_task),
	url(r'^progress-problems/$', views.progress_problems, name='progress_problems'),
	url(r'^progress-scans/$', views.progress_scans, name='progress_scans'),
	url(r'^ajax/submit-scan/$', views.ajax_submit_scan),
	url(r'^ajax/next-scan/$', views.ajax_next_scan),
	url(r'^ajax/prev-evidence/$', views.ajax_prev_evidence),
	url(r'^ajax/submit-match/$', views.ajax_submit_match),
	url(r'^ajax/next-match/$', views.ajax_next_match),
	url(r'^ajax/task-query/$', views.ajax_task_query),
	url(r'^reports/short/$', views.reports_short, name='results_short'),
	url(r'^reports/extended/$', views.reports_extended, name='results_extended'),
	url(r'^reports/full/$', views.reports_full, name='reports_full'), # super-user only
	url(r'^reports/teaser/$', views.reports_teaser, name='reports_teaser'), # public
	url(r'^reports/spreadsheet/$', views.reports_spreadsheet, name='reports_spreadsheet'), # super-user only
	url(r'^reports/awards/$', views.reports_awards, name='reports_awards'),
	url(r'^management/([a-zA-Z]+)/$', views.run_management, name='manage'),
	url(r'^scoreboard$', views.scoreboard, name='scoreboard'),
	url(r'^scoreboard/update$', views.scoreboardUpdate, name="scoreboardupdate"),
	url(r'^$', views.index, name='index')
]
# TODO: should really use URL patterns here, sorry
# didn't know they existed back when I wrote this thing

models.py
"""
HELIUM 2
(c) 2017 Evan Chen
See LICENSE.txt for details.

models.py

General overview of models:

* Entity objects represent either a team or mathlete
* These Entity's takes several Exams, with several Problems
* For every Entity and Problem, we have a Verdict (which gives the score)
  based on Evidence (one for each grader who read the problem)
* ExamScribble and ProblemScribble objects keep track of scans
* EntirePDFScribble is a container for keeping track of uploaded PDF's
* GutsScoreFunc is a stupid applet that lets you compute guts estimation scores
* ScoreRow is used for the caching of score results
* ThreadTask is used for the management of async tasks (see threader.py)


Notes on data creation:

* The Exam and Guts Scoring Function objects are meant to be edited
  directly through the admin interface.
* The Entity table is populated using the command heliumimport.


"""



from django.db import models
from django.dispatch import receiver
from django.contrib.auth import models as auth
from django.core.exceptions import ValidationError
import logging
import collections

# Originally referenced registration models,
# but it seemed cleaner to just create a copy of the data here,
# so that (i) Helium is entirely divorced from registration,
# (ii) makes it easier to use Helium externally,
# (iii) reg models not written by me and all code not by me is bad.
# Actually re (iii) the whole {Mathlete/Team}{Nov/Feb} is bad
# and I think it should go die in a burning hole

# Moreover, teams and mathletes really should be the same object
# (namely, "contest takers")


### CONTESTANT Objects ###

# These are used to provide Entity.teams and Entity.mathletes
class TeamManager(models.Manager):
	def get_queryset(self):
		return super(TeamManager, self).get_queryset().filter(is_team = True)
class MathleteManager(models.Manager):
	def get_queryset(self):
		return super(MathleteManager, self).get_queryset().filter(is_team=False)

class Entity(models.Model):
	"""This represents EITHER a team or a mathlete --- i.e. a test taker.
	There are managers Entity.teams and Entity.mathletes to grab either
	(as well as Entity.objects, as usual).
	
	The `team` attribute points to another Entity,
	and should be set to None for (i) actual teams, and (ii) individuals without teams.
	In particular, in a contest with no teams this should always be None.
	The Boolean is_team distinguishes between use cases (i) and (ii).
	
	In addition to Entity.objects, the managers Entity.teams and Entity.mathletes."""

	name = models.CharField(max_length=80)
	shortname = models.CharField(max_length=80, default='', blank=True,
			help_text = "For teams, a shorter version of their name. "
			"This is used instead when attached to mathletes. "
			"Leave this blank to just use the team name instead. "
			"Leave this blank for individuals.")
	team = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
	is_team = models.BooleanField(default=False)
	number = models.IntegerField(null=True, blank=True,
			help_text = "You can assign (unique) numbers here "
			"if you can't assume names are pairwise distinct."
			"This isn't used internally by Helium itself.")
	# This shouldn't be marked unique=True since unique_together later on with team

	def clean(self):
		if self.team is not None and self.is_team:
			raise ValidationError("LOL what?")

	def __str__(self):
		if self.team is not None:
			if self.team.shortname:
				return '%s [%s]' %(self.name, self.team.shortname)
			else:
				return '%s [%s]' %(self.name, self.team.name)
		elif self.is_team:
			if self.shortname:
				return '%s (%s)' %(self.name, self.shortname)
			else:
				return self.name
		else:
			return self.name

	@property
	def verbose_name(self):
		if self.team is not None:
			if self.team.shortname:
				name = '%s [%s / %s]' %(self.name, self.team.name, self.team.shortname)
			else:
				name = '%s [%s]' %(self.name, self.team.name)
		elif self.is_team:
			if self.shortname:
				name = '%s / %s' %(self.name, self.shortname)
			else:
				name = self.name
		else:
			name = '%s [Individual]' % self.name
		if self.number is not None:
			name = '#' + str(self.number) + " " + name
		return name


	objects = models.Manager() # why do I have to repeat this?
	teams = TeamManager()
	mathletes = MathleteManager()

	def size(self):
		"""This is the size of a team (or None on individuals)"""
		if not self.is_team: return None
		else: return self.entity_set.count()

	class Meta:
		unique_together = ('is_team', 'number')

# Exam/problem objects

class Exam(models.Model):
	name = models.CharField(max_length=50, help_text = 'Name of exam', unique = True)
	color = models.CharField(max_length=50, default="#FFFFFF",\
			help_text="Color which exam is printed on. "
			"Grading pages will be tinted with this color so that e.g. "
			"we don't accidentally have someone enter Algebra scores into Geometry. "
			"(This was a very common mistake in old Babbage.) "
			"This color is page background so it should be VERY light (like #EEFFEE light).")
	is_indiv = models.BooleanField(default=True)
	is_ready = models.BooleanField(default=True,
			help_text = "Mark true if you want users to be able to grade this exam. "
			"You should set it to False if you are waiting for scans for example. "
			"You can also set it to False after the exam is *done* grading, "
			"so as not to distract users. "
			"Note that this does not affect validation, it only affects the UI: "
			"in other words users can still navigate directly to a URL to grade this exam.")
	can_upload_scan = models.BooleanField(default=False,
			help_text = "Mark true if you want users to be able to upload scans this exam. "
			"You should set it to False after all exams are scanned, "
			"to decrease the chance that someone uploads a scan to the wrong place.")
	is_alg_scoring = models.BooleanField(default=True,
			help_text = "Whether this test should use algorithmic scoring "
			"to have problem weights determined for it.")
	is_scanned = models.BooleanField(default=False,
			help_text = "Whether the scan grader will show this problem or not. "
			"For example, this should almost certainly be False for Guts round.")
	uses_qr = models.BooleanField(default=False,
			help_text = "Whether to enable QR codes for name matching for this test. ")

	min_grades = models.IntegerField(default=3,
			help_text="This is the minimum number of graders required before "
			" a problem is marked as `done grading` by the system.")
	min_override = models.IntegerField(default=5,
			help_text="Number of graders required to override a grading conflict. "
			"For example, the default setting is that a 5:1 majority is sufficient "
			"to override a conflicting grade.")

	def __str__(self): return self.name

	@property
	def takers(self):
		'''The students taking this exam'''
		return Entity.mathletes if self.is_indiv else Entity.teams

	@property
	def problems(self):
		return self.problem_set.order_by('problem_number')

class Problem(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	problem_number = models.IntegerField(help_text = "Must be unique per exam.")
	answer = models.CharField(max_length=70, default='', blank=True,
			help_text = "The answer for a problem, which is shown in help texts.")

	weight = models.FloatField(default=1,
			help_text = "This is the weight of the problem. "
			"For tests with algorithmic scoring, this is overwritten later with beta values, "
			"and therefore the value of the weight is unimportant. "
			"For tests scored traditionally this weight should be an integer.")
	allow_partial = models.BooleanField(default=False,
			help_text = "If true, all recorded scores should be 0 or 1. "
			"If false, all recorded scores should be integers from 0 to the weight.")
	def __str__(self): return self.exam.name + " #" + str(self.problem_number)

	@property
	def is_indiv(self):
		return self.exam.is_indiv

	@property
	def intweight(self):
		return int(self.weight) if self.weight.is_integer() else self.weight

	class Meta:
		unique_together = ('exam', 'problem_number')

# Grading Objects

class Verdict(models.Model):
	"""The Verdict object represents a collection of EVIDENCES,
	which are attached to a pair of (problem, entity).
	For example, `Algebra #3 score for Evan.`
	The entity will be None if grading a scan which has not yet been matched with an entity.
	"""
	problem = models.ForeignKey(Problem, on_delete=models.CASCADE) # You should know which problem

	# You might have verdicts for which you don't know whose yet
	# because the verdict is created by a to-be-matched scribble
	entity = models.ForeignKey(Entity, blank=True, null=True,
			help_text = "This should be None for scans which have not yet been matched.", on_delete=models.CASCADE)
	score = models.IntegerField(blank=True, null=True,
			help_text = "This should be 0 or 1 for all-or-nothing problems, "
			"and the actual score for problems which have weights. "
			"You should not need to touch this setting; it is auto-computed.")
	is_valid = models.BooleanField(default=True,
			help_text = "This is True if there are no conflicts in grading "
			"as determined by the min_override setting of the exam. "
			"You should not need to touch this setting; it is auto-computed.")
	is_done = models.BooleanField(default=False,
			help_text = "Whether this verdict should be read by more normal users "
			"as determined by the min_grades setting of the exam. "
			"You should not need to touch this setting; it is auto-computed.")
	scanned_at = models.DateTimeField(blank=True, null=True,
			help_text = "When the verdict was created based on scans. "
			"None if the Verdict isn't associated to a scan. "
			"Should not be edited manually. "
			"This is actually a hack to deal with bulk_update issues")

	def __str__(self):
		if self.entity is not None:
			who = str(self.entity)
		else:
			who = 'ID %05d' % self.id
		return str(self.problem) + ': ' + who

templates/helium/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,700|Raleway:400,500,600,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static 'hijack/hijack-styles.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    {% block helium-stylesheets %}{% endblock %}
</head>

<body>
    {% if debug %}
    <div id="debug-warning" class="alert" role="alert">
        Site currently in <b style="color:red;">DEBUG</b> mode.
    </div>
    {% endif %}

    <div id="page-wrapper">
    {% block navbar %}
    <div id="helium-nav">
      <a href="/helium">&lt; Back to Helium home</a>
      <ul class="nav navbar-right">
        {% if user.is_authenticated %}
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="padding-top: 0px">{{ user }}<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <li><a href="/helium">Helium Dashboard</a></li>
          {% if user.is_superuser %}
          <li><a href="/admin">Django Admin</a></li>
          {% endif %}
          <li><a href="/admin/logout">Log Out</a></li>
          </ul>
        </li>
        {% else %}
        <li class="dropdown">
          <span><a href="/admin/login">Log In</a></span>
        </li>
        {% endif %}
        </li>
      </ul>
      <div style="clear: both;"></div>
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
    </div>
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script> 

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-65249351-1', 'auto');
      ga('send', 'pageview');
    </script>

    {% block helium-scripts %}{% endblock %}
    {% block scripts %}{% endblock %}

    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
        });
        MathJax.Hub.Config({
        "HTML-CSS": { linebreaks: { automatic: true } },
                SVG: { linebreaks: { automatic: true } }
        });
    </script>

    <script type="text/javascript" async
        src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
    </script>
</body>
</html>

templates/helium/fast-match.html
{% extends 'helium/layout.html' %}
{% load static %}

{% block pagetitle %}Fast Match: {{ exam }}{% endblock %}

{% block layout-content %}
<p><i>Instructions:</i> 
Students should hopefully have provided their correct student or team number,
which will make this matching process a whole lot less painful.
Input a number, and the corresponding candidate will appear.
Press enter to confirm this choice.
Alternatively, one can search for the name in the autocomplete field.
</p>

<p>You can use "view full scan" above to see the entire scanned page.</p>
<div class="scanstage">
	<a class="scanzoom" src="" id="zoom_url" target="_blank"/>(View Full Scan)</a>
	<img class="scan" src="" id="scan_img" />
</div>
<div id="controls">
<p><button id="button_decr_index">Go Back</button>
<button id="button_incr_index">Skip</button></p>
<div id="attention_reason" class="text-warning"></div>
<form id="entity_selector" action="#">
	<p><label>Input Number:</label> <input id="magic_box" name="magic_box" /> then press Enter</p>
	<p>Or, find the name of the entity from below:</p>
	<p>{{ widgetHTML }}</p>
	<p>Or, if there is some issue, explain below (and press submit).
	Entering text below will clear any selections above.</p>
	<textarea rows="3" cols="50" id="attention"></textarea>
	<p><input type="submit" /></p>
</form>
</div>
{% if show_attention %}
<p>Currently, the system is set to <b>only display scribbles</b>
which need special attention.</p>
{% elif request.user.is_superuser %}
<p>To see scribbles which <b>need attention</b>, <a href="attention">click here</a>.</p>
{% endif %}


{% endblock %}

{% block scripts %}
<script type="text/javascript">
var regnum_to_id = {
	{% for entity in entities %} {{ entity.number }} : {{ entity.id }}, {% endfor %} 
};
</script>

<script type="text/javascript">
$(document).ready(function() {
	// We have a stream of data objects, which are tuples of ID's and whatnot
	// current_index points to the one we are currently reading

	// Stream of data objects. We'll preload images using this.
	// Items are ordered pairs (examscribble id, examscribble url)
	// current_index describes which one we currently have
	var stream = [];
	var current_index = 0; // the current index inside the stream
	var esid = 0; // current exam scribble's ID
	var pos = 0; // scribble ID at end of stream

	var is_waiting = true;
	// This flag is set to true if the queue is empty
	// and load_scan_at_current_index cannot find an image.
	// This causes the preload_next_scan to call
	// load_next_scan when it finishes.

	function preload_next_scan(n) {
		$.ajax({
			url  : "/helium/ajax/next-match/",
			type : "POST",
			data : {
				exam_id : {{ exam.id }},
				num_to_load : n,
				show_attention : {{ show_attention }},
				pos : pos,
			},
		}).done(function(result) {
			for (var i=0; i<result.length; i++) {
				var data = result[i];
				stream.push(data);
				pos = data[0];
				$('<img />').attr('src', data[1]); // preload the image
				if (is_waiting) { // If pending, load next scan
					is_waiting = false;
					load_scan_at_current_index(); // try again
				}
			}
		});
	}
	preload_next_scan(3); // preload three scans

	function load_scan_at_current_index() {
		$("#magic_box").val(''); // reset
		$("#candidate").html(''); // reset
		if (stream.length <= current_index) {
			// No next item to grab: defer until after next preload call
			is_waiting = true;
		}
		else {
			// Push to next guy
			next_data = stream[current_index];
			// Meow
			esid = next_data[0]; // next examscribble
			var image_url  = next_data[1];
			$("#scan_img").attr('src', image_url);
			if (esid != 0) {
				$("#scan_id").html(esid);
				$("#zoom_url").attr('href',
						'/helium/view-paper/scan/' + esid + '/#scan');
				$("#attention").val(next_data[2]);
				$("#attention_reason").html(next_data[2]);
			}
		}
		console.log(stream);
		console.log(current_index);
	}

	function updateUI(id) {
		$("#id_entity").val(id);
		if (id != "")
			$(".ui-autocomplete-input").val($("#id_entity option:selected").text());
		else
			$(".ui-autocomplete-input").val("");
	}

	// On keypress in magic box
	$("#magic_box").keyup(function (e) {
		if (esid == 0) return; // nothing to do
		var value = $("#magic_box").val();
		$("#attention").val('');
		console.log(value);
		if (value in regnum_to_id) updateUI(regnum_to_id[value]);
		else updateUI("");
	});
	$(".ui-autocomplete-input").change(
			function (e) { $("#attention").val(''); }
	);

	$("#attention").keyup(function() {
		if ($.trim($("#attention").val()) != "") {
			$("#magic_box").val('');
			updateUI('');
		}
	});

	$("#entity_selector").submit(function() {
		var attention = $.trim($("#attention").val());
		console.log(attention);
		if (($("#id_entity").val() == "") && (attention == ""))
			return false;
		$.ajax({
			url  : "/helium/ajax/submit-match/",
			type : "POST",
			data : { examscribble_id : esid,
				entity_id : $("#id_entity").val(),
				attention: attention},
		});
		updateUI("");
		$("#attention").val(""); // empty attention box

		preload_next_scan(1);
		current_index++; // Move to next one
		load_scan_at_current_index();
		return false; // prevent page from submitting
	});

	$("#button_decr_index").click(function() {
		if (current_index > 0) current_index--;
		load_scan_at_current_index();
	});
	$("#button_incr_index").click(function() {
		if (esid == 0) return;
		current_index++;
		preload_next_scan(1);
		load_scan_at_current_index();
	});

	load_scan_at_current_index(); // load first image
	$("#magic_box").focus();
	$("#id_entity").val("");
	$(".ui-autocomplete-input").val("");
});
</script>
{% endblock %}

templates/helium/find-paper.html
{% extends 'helium/layout.html' %}
{% load static %}

{% block pagetitle %}Find Papers{% endblock %}

{% block layout-content %}
<p>In this interface you can look up all the
verdicts and evidence for a specific
entity and exam.</p>

<h4>Search by Name</h4>
{% include 'helium/form.html' with form=eesform submit_name="Look up" %}

<h4>Search by PDF</h4>
<form action="{% url 'view_pdf_redir' %}" method="post">
	<div class="clearfix">
		<div class="col-xs-8">
		{% csrf_token %}
		{{ pdfform.as_p }}
		</div>
		<div class="col-xs-4">
		<input type="submit" name="from_landing" value="View Pages" />
		</div>
	</div>
</form>

{% if show_attention %}
<h4>Exam Scribbles Needing Attention</h4>
{% include 'helium/table.html' %}
{% endif %}


{% endblock %}

templates/helium/layout.html
{% extends 'helium/base.html' %}
{% load static %}

{% block helium-stylesheets %}
<link href="{% static 'css/helium.css' %}" rel="stylesheet">
{% if exam %}
<style type="text/css">
body { background-color: {{ exam.color }}; }
</style>
{% endif %}
{% endblock %}

{% block content %}
  {% block layout-header %}
  <section id="banner">
	  <a href="{% url 'index' %}"><img src="{% static 'img/balloons.png' %}"/></a>
  </section>
  <p><a href="{% url 'index' %}">&lt; Back to Helium home</a></p>
  {% endblock %}
  <section id="body-form">
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  <h3>{% block pagetitle %}{% endblock %}</h3>
  {% block layout-content %}
  {% endblock %}
  <hr />
  </section>

  {% block layout-footer %}
  <section id="footer">
  <p><a href="{% url 'index' %}">&lt; Back to Helium home</a></p>
  <p>Helium &copy; 2017 Evan Chen</p>
  </section>
  {% endblock %}
{% endblock %}

{% block helium-scripts %}
<script type="text/javascript" src="{% static 'js/autoselect.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (settings.type == 'POST' && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
  }}});

  var autocomplete_options = {
    'relevancy-sorting': false,
    'alternative-spellings' : false,
    'sort': false,
    'delay': 250, // seems to not do anything? sad
  }

  $("#id_entity[type!=\"hidden\"]").selectToAutocomplete(autocomplete_options);
  $("#id_mathlete[type!=\"hidden\"]").selectToAutocomplete(autocomplete_options);
  $("#id_team[type!=\"hidden\"]").selectToAutocomplete(autocomplete_options);

  var angle = 0;
  $("#rotate_link").click(function() {
    angle += 180;
    $("#scan_img").css('transform', 'rotate('+angle+'deg)');
  });
});
</script>
{% endblock %} 

templates/helium/old-grader.html
{% extends 'helium/layout.html' %}
{% load static %}

{% block pagetitle %}Classical Grader: {{ exam }}{% endblock %}

{% block layout-content %}
{% if exam.is_scanned %}
<p><b>Warning</b>: this exam is supposed to be graded by scan.
Proceed with utmost caution.
Do not continue if you don't know what this means.</p>
{% endif %}

<p>Enter scores below, using binary scores for all-or-nothing problems.
Ideally, you should enter all of data,
but if you leave certain fields blank they will not be processed.</p>

<p>The system will alert you if you have a merge conflict.
If you are confident your own entered entry is correct,
you should use the "override" button below.</p>

<p>Use <a target="_new" href="{% url 'estimation_calc' %}">this widget</a>
for grading Guts estimation questions.</p>

{% include "helium/form.html" with form=form submit_name="Enter Scores" %}
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/autoselect.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
	function update(){
		if ( $("#id_entity").val() ) {
			$.ajax({
				url  : "/helium/ajax/prev-evidence/",
				type : "POST",
				data : {
					entity_id : $("#id_entity").val(),
					exam_id : {{ exam.id }}
				},
			}).done( function(result) {
				var encountered_null = false;
				for (var i=0; i<result.length; ++i) {
					var n = result[i][0];
					var s = result[i][1];
					$("#id_p" + n).val(s);
					if (s == null && !encountered_null) {
						$("#id_p" + n).focus(); // Focus on that one
						encountered_null = true;
					}
				}
			})
		}
	}
	$('#id_entity').change(update);
	update(); // Run initial update
});
</script>
{% endblock %}

templates/helium/upload-scans.html
{% extends 'helium/layout.html' %}
{% load static %}

{% block pagetitle %}Upload Scans{% endblock %}

{% block layout-content %}

{% include "helium/form.html" with form=form submit_name="Upload" has_upload=True %}

{% endblock %}